### ISSUE TITLE
QNG version 2.0.2+dev-862d4c6 / amana multi node private/consortium chain issues 

### ISSUE THREAD

**Issue by wyonghao** [Qitmeer/qng#793] opened 2024-09-28 09:46 UTC
We are trying to use QNG 2.0.x for a private/consortium chain. 
1) firstly , when we tested the single node, we encounter the node restarting and losing blocks:
```
2024-09-23|12:44:11.312 [INFO ] Loaded most recent local block number=107,074 hash=0d690c..9220c2 td=214,149 age=10h37m2s
2024-09-23|12:44:11.313 [INFO ] Loaded most recent local finalized block number=107,072 hash=6b3bc8..f3a2f8 td=214,145 age=10h37m12s
2024-09-23|12:44:11.313 [WARN ] Head state missing, repairing number=107,074 hash=0d690c..9220c2 snaproot=6479e7..856eff
2024-09-23|12:44:16.102 [INFO ] Rewound to block with state number=382 hash=89b13b..fec3e9
```
2) our team spent 5h trying to start afresh with 3 nodes, but we ran into some technical problems. in order to set this 5-node (3 Validators + 2 rpc) on 3 separate VMs as we're quite lost in the multitude of settings, especially with Amana and evm running in the same node. There were a couple of issues our team noticed with Amana when running the nodes. our theory is it has to do with the Shanghai/Cancun fork implementation which for the time being may not be stable.

we might have an issue with the "clique" proof-of-authority consensus mechanism implemented in geth, as after a while it ends in a deadlock state.
![image](https://github.com/user-attachments/assets/72609038-8f95-4aa4-963d-fee0894b18dd)
![image](https://github.com/user-attachments/assets/14a00485-8b6c-4625-a733-ec59072d2322)

We read some articles regarding this issue and compiled a trace which led towards hyperledger besu implementing the potential solutions:
 
it could be this issue:
[PoA network, all the sealers are waiting for each other after 2 months running, possible deadlock? · Issue #18402 · ethereum/go-ethereum · GitHub](https://github.com/ethereum/go-ethereum/issues/18402)
 
which had recent questions in here:
[Theoretical Issues with Clique · Issue #7437 · hyperledger/besu · GitHub](https://github.com/hyperledger/besu/issues/7437)
 
explained and theoretically resolved in here:
[EIP-3436: Expanded Clique Block Choice Rule (ethereum.org)](https://eips.ethereum.org/EIPS/eip-3436)
 
and implemented in hyperledger besu in here
[EIP-3436 - Expanded Clique Block Choice Rule by shemnon · Pull Request #2084 · hyperledger/besu · GitHub](https://github.com/hyperledger/besu/pull/2084)

3) After local testing, we noticed a different issue where authorised validators are unable to produce blocks after authorising and adding a different validator onto the network (using the amana.propose() function. we are looking into fixing this issue otherwise we will not be able to add more validators after the network has started running.

Can team provide some help on above issues that we have met ? thank you !

**Comment by dindinw** [comment] 2024-09-29 02:30
@wyonghao
Please try the latest build **QNG version 2.0.2+dev-e43bbd1** （#795）
We think it should resolve this issue.
For the issue EIP-3436, we will do more research.

**Comment by dindinw** [comment] 2024-10-08 07:17
the issue is closed as there is no further input.

**Closed as completed by dindinw** 2024-10-08 07:17 UTC
